version: '3'
services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: app
    working_dir: /var/www
    depends_on:
      - mysql
    volumes:
      - ".:/var/www/"
    networks:
      - app_net

  mysql:
    image: mariadb:10.4
    container_name: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: presu
      MYSQL_USER: presu
      MYSQL_PASSWORD: secret
    networks:
      - app_net

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - app
    volumes:
      - ".:/var/www/"
      - "./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    networks:
      - app_net

networks:
  app_net:

volumes:
  mysql_data: